// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlutescdhevmbftqqsji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdXRlc2NkaGV2bWJmdHFxc2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTgwMjEsImV4cCI6MjA2MzU3NDAyMX0.qiOy3Kosv3DaIwNjjMZ5r-ojEoXh1PV4jACKWr1cqKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);